### ISSUE TITLE
LinkedIn r_basicprofile

### ISSUE THREAD

**Issue by zacid** [fajarmf/ueberauth_linkedin#6]
I don't seem to be getting all requested fields back from LinkedIn.

According to doc, 'r_basicprofile' is specified as default but I get back:

`info: %Ueberauth.Auth.Info{description: nil, email: "zac@gmail.com",
  first_name: "Zac",
  image: "https://media.licdn.com/mpr/mprx/",
  last_name: "last_name", location: nil, name: nil, nickname: nil, phone: nil,
  urls: %{}}, provider: :linkedin, strategy: Ueberauth.Strategy.LinkedIn,
 uid: "123"}`

Is the basic profile not meant to contain all fields as per specified here: https://developer.linkedin.com/docs/fields/basic-profile ?

**Comment by zacid** [comment]
Ahha, after a bit more digging I've noticed that it's because this information is _not_ requested subsequent to the oAuth permission grant.

I've found this here: https://github.com/fajarmf/ueberauth_linkedin/blob/master/lib/ueberauth/strategy/linkedin.ex#L130

Is this by design or can 'location' and other fields be added and thus also added to the '%Info{}' struct?

If so I'll be willing to do a PR, otherwise what would you say the best way to specify what information you're trying to get would be?

**Comment by fajarmf** [comment]
Hi,

Thank you for figuring this out. I haven't had time to work on this library again. So could you send a PR?

**Comment by arjan** [comment]
Should be fixed with #11 now.

**Comment by arjan** [comment]
@fajarmf If you have no time or do not feel like maintaining this anymore, I'm happy to take over or help maintaining it.
